dist: bionic

language: cpp

services:
  - docker

install: true

script:
  - docker build -t yasa .
  - docker run --name yasa-container yasa
  - docker cp yasa-container:/usr/local/src/yasa/build/coverage.info .
  - wget -S -O - https://codecov.io/bash | bash
