dist: bionic

language: cpp

services:
  - docker

install: true

script:
  - docker build -t yasa .
  # execute the container to get the coverage report
  - docker run --detach --interactive --name yasa-container yasa --version
  - docker cp yasa-container:/usr/local/src/yasa/debug-build/coverage.info .
  - wget -S -O - https://codecov.io/bash | bash
  - ./run_example.sh  # integration test
