dist: bionic

language: cpp

services:
  - docker

install: true

script:
  - docker build -t yasa .
  - docker run --detach --interactive --name yasa-container yasa /bin/bash
  - docker cp yasa-container:/usr/local/src/yasa/debug-build/coverage.info .
  - wget -S -O - https://codecov.io/bash | bash
  - docker exec yasa-container /bin/bash -c "yasa train -n example/neg -p example/pos; yasa classify -f example/neg.txt; yasa classify -f example/pos.txt"
